In [1]:
import numpy, scipy, matplotlib.pyplot as plt, pandas, librosa

In [3]:
print (numpy.arange(5))

[0 1 2 3 4]


In [4]:
print (numpy.linspace(0, 5, 10, endpoint=False))

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [5]:
print (numpy.zeros(5))

[0. 0. 0. 0. 0.]


In [6]:
print (numpy.ones(5))

[1. 1. 1. 1. 1.]


In [7]:
print (numpy.ones((5,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
print (scipy.randn(5)) # random Gaussian, zero-mean unit-variance

[-0.57098167  0.08543233  1.2491067   0.92584553  0.00390102]


In [10]:
print (scipy.randn(5,2))

[[ 0.98242488  0.42548959]
 [ 0.08728754 -1.28759113]
 [-0.39017212  0.3357771 ]
 [ 1.51067084  1.64708491]
 [ 0.62067143 -0.12739363]]


In [11]:
x = numpy.arange(10)
print (x[2:4])

[2 3]


In [12]:
print (x[-1])

9


In [13]:
print (x[0:8:2])

[0 2 4 6]


In [14]:
print (x[4:2:-1])

[4 3]


In [15]:
print (x[:4])

[0 1 2 3]


In [16]:
print (x[:999])

[0 1 2 3 4 5 6 7 8 9]


In [17]:
print (x[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [18]:
x = numpy.arange(5)
y = numpy.ones(5)
print (x+2*y)

[2. 3. 4. 5. 6.]


In [19]:
x = scipy.randn(5)
y = numpy.ones(5)
print (numpy.dot(x, y))

-2.9042929639030928


In [20]:
x = scipy.randn(5,3)
y = numpy.ones((3,2))
print (numpy.dot(x, y))

[[ 0.28115174  0.28115174]
 [ 1.36621044  1.36621044]
 [-0.56559484 -0.56559484]
 [-1.02853779 -1.02853779]
 [-0.33311275 -0.33311275]]


In [21]:
x = numpy.arange(10)
print (x < 5)

[ True  True  True  True  True False False False False False]


In [22]:
y = numpy.ones(10)
print (x < y)

[ True False False False False False False False False False]


In [23]:
from scipy.spatial import distance
print (distance.euclidean([0, 0], [3, 4]))
print (distance.sqeuclidean([0, 0], [3, 4]))
print (distance.cityblock([0, 0], [3, 4]))
print (distance.chebyshev([0, 0], [3, 4]))

5.0
25.0
7
4


In [24]:
print (distance.cosine([67, 0], [89, 0]))
print (distance.cosine([67, 0], [0, 89]))

0.0
1.0


In [26]:
x = scipy.randn(5)
print (x)
x.sort()
print (x)

[-0.12093561  0.7855796   1.36284502 -0.22748491 -2.52941382]
[-2.52941382 -0.22748491 -0.12093561  0.7855796   1.36284502]


In [27]:
x = scipy.randn(5)
print (x)
ind = numpy.argsort(x)
print (ind)
print (x[ind])

[-0.40997493 -0.18479772 -0.38469508 -0.13474965  0.67913475]
[0 2 1 3 4]
[-0.40997493 -0.38469508 -0.18479772 -0.13474965  0.67913475]
